//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: bluetooth.proto

package com.example.transport;

@kotlin.jvm.JvmName("-initializeclientMessage")
public inline fun clientMessage(block: com.example.transport.ClientMessageKt.Dsl.() -> kotlin.Unit): com.example.transport.ClientMessage =
  com.example.transport.ClientMessageKt.Dsl._create(com.example.transport.ClientMessage.newBuilder()).apply { block() }._build()
public object ClientMessageKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.example.transport.ClientMessage.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: com.example.transport.ClientMessage.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): com.example.transport.ClientMessage = _builder.build()

    /**
     * <code>.base.Move move = 1;</code>
     */
    public var move: com.example.transport.Move
      @JvmName("getMove")
      get() = _builder.getMove()
      @JvmName("setMove")
      set(value) {
        _builder.setMove(value)
      }
    /**
     * <code>.base.Move move = 1;</code>
     */
    public fun clearMove() {
      _builder.clearMove()
    }
    /**
     * <code>.base.Move move = 1;</code>
     * @return Whether the move field is set.
     */
    public fun hasMove(): kotlin.Boolean {
      return _builder.hasMove()
    }

    /**
     * <code>.base.ClientAction action = 2;</code>
     */
    public var action: com.example.transport.ClientAction
      @JvmName("getAction")
      get() = _builder.getAction()
      @JvmName("setAction")
      set(value) {
        _builder.setAction(value)
      }
    /**
     * <code>.base.ClientAction action = 2;</code>
     */
    public fun clearAction() {
      _builder.clearAction()
    }
    /**
     * <code>.base.ClientAction action = 2;</code>
     * @return Whether the action field is set.
     */
    public fun hasAction(): kotlin.Boolean {
      return _builder.hasAction()
    }
    public val payloadCase: com.example.transport.ClientMessage.PayloadCase
      @JvmName("getPayloadCase")
      get() = _builder.getPayloadCase()

    public fun clearPayload() {
      _builder.clearPayload()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.example.transport.ClientMessage.copy(block: com.example.transport.ClientMessageKt.Dsl.() -> kotlin.Unit): com.example.transport.ClientMessage =
  com.example.transport.ClientMessageKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public val com.example.transport.ClientMessageOrBuilder.moveOrNull: com.example.transport.Move?
  get() = if (hasMove()) getMove() else null

