//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: base.proto

package com.example.transport;

@kotlin.jvm.JvmName("-initializemove")
public inline fun move(block: com.example.transport.MoveKt.Dsl.() -> kotlin.Unit): com.example.transport.Move =
  com.example.transport.MoveKt.Dsl._create(com.example.transport.Move.newBuilder()).apply { block() }._build()
public object MoveKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.example.transport.Move.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: com.example.transport.Move.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): com.example.transport.Move = _builder.build()

    /**
     * <code>uint32 row = 1;</code>
     */
    public var row: kotlin.Int
      @JvmName("getRow")
      get() = _builder.getRow()
      @JvmName("setRow")
      set(value) {
        _builder.setRow(value)
      }
    /**
     * <code>uint32 row = 1;</code>
     */
    public fun clearRow() {
      _builder.clearRow()
    }

    /**
     * <code>uint32 col = 2;</code>
     */
    public var col: kotlin.Int
      @JvmName("getCol")
      get() = _builder.getCol()
      @JvmName("setCol")
      set(value) {
        _builder.setCol(value)
      }
    /**
     * <code>uint32 col = 2;</code>
     */
    public fun clearCol() {
      _builder.clearCol()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.example.transport.Move.copy(block: com.example.transport.MoveKt.Dsl.() -> kotlin.Unit): com.example.transport.Move =
  com.example.transport.MoveKt.Dsl._create(this.toBuilder()).apply { block() }._build()

