//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: network.proto

package com.example.transport;

@kotlin.jvm.JvmName("-initializecreateResponse")
public inline fun createResponse(block: com.example.transport.CreateResponseKt.Dsl.() -> kotlin.Unit): com.example.transport.CreateResponse =
  com.example.transport.CreateResponseKt.Dsl._create(com.example.transport.CreateResponse.newBuilder()).apply { block() }._build()
public object CreateResponseKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.example.transport.CreateResponse.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: com.example.transport.CreateResponse.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): com.example.transport.CreateResponse = _builder.build()

    /**
     * <code>.base.GameStatus status = 1;</code>
     */
    public var status: com.example.transport.GameStatus
      @JvmName("getStatus")
      get() = _builder.getStatus()
      @JvmName("setStatus")
      set(value) {
        _builder.setStatus(value)
      }
    /**
     * <code>.base.GameStatus status = 1;</code>
     */
    public fun clearStatus() {
      _builder.clearStatus()
    }
    /**
     * <code>.base.GameStatus status = 1;</code>
     * @return Whether the status field is set.
     */
    public fun hasStatus(): kotlin.Boolean {
      return _builder.hasStatus()
    }

    /**
     * <code>.base.WinLine win_line = 2;</code>
     */
    public var winLine: com.example.transport.WinLine
      @JvmName("getWinLine")
      get() = _builder.getWinLine()
      @JvmName("setWinLine")
      set(value) {
        _builder.setWinLine(value)
      }
    /**
     * <code>.base.WinLine win_line = 2;</code>
     */
    public fun clearWinLine() {
      _builder.clearWinLine()
    }
    /**
     * <code>.base.WinLine win_line = 2;</code>
     * @return Whether the winLine field is set.
     */
    public fun hasWinLine(): kotlin.Boolean {
      return _builder.hasWinLine()
    }

    /**
     * <code>uint32 game_id = 4;</code>
     */
    public var gameId: kotlin.Int
      @JvmName("getGameId")
      get() = _builder.getGameId()
      @JvmName("setGameId")
      set(value) {
        _builder.setGameId(value)
      }
    /**
     * <code>uint32 game_id = 4;</code>
     */
    public fun clearGameId() {
      _builder.clearGameId()
    }
    /**
     * <code>uint32 game_id = 4;</code>
     * @return Whether the gameId field is set.
     */
    public fun hasGameId(): kotlin.Boolean {
      return _builder.hasGameId()
    }

    /**
     * <code>optional .base.Move move = 5;</code>
     */
    public var move: com.example.transport.Move
      @JvmName("getMove")
      get() = _builder.getMove()
      @JvmName("setMove")
      set(value) {
        _builder.setMove(value)
      }
    /**
     * <code>optional .base.Move move = 5;</code>
     */
    public fun clearMove() {
      _builder.clearMove()
    }
    /**
     * <code>optional .base.Move move = 5;</code>
     * @return Whether the move field is set.
     */
    public fun hasMove(): kotlin.Boolean {
      return _builder.hasMove()
    }
    public val CreateResponseKt.Dsl.moveOrNull: com.example.transport.Move?
      get() = _builder.moveOrNull
    public val payloadCase: com.example.transport.CreateResponse.PayloadCase
      @JvmName("getPayloadCase")
      get() = _builder.getPayloadCase()

    public fun clearPayload() {
      _builder.clearPayload()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.example.transport.CreateResponse.copy(block: com.example.transport.CreateResponseKt.Dsl.() -> kotlin.Unit): com.example.transport.CreateResponse =
  com.example.transport.CreateResponseKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public val com.example.transport.CreateResponseOrBuilder.winLineOrNull: com.example.transport.WinLine?
  get() = if (hasWinLine()) getWinLine() else null

public val com.example.transport.CreateResponseOrBuilder.moveOrNull: com.example.transport.Move?
  get() = if (hasMove()) getMove() else null

