//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: network.proto

package com.example.transport;

@kotlin.jvm.JvmName("-initializecreateRequest")
public inline fun createRequest(block: com.example.transport.CreateRequestKt.Dsl.() -> kotlin.Unit): com.example.transport.CreateRequest =
  com.example.transport.CreateRequestKt.Dsl._create(com.example.transport.CreateRequest.newBuilder()).apply { block() }._build()
public object CreateRequestKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.example.transport.CreateRequest.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: com.example.transport.CreateRequest.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): com.example.transport.CreateRequest = _builder.build()

    /**
     * <code>.base.Move move = 1;</code>
     */
    public var move: com.example.transport.Move
      @JvmName("getMove")
      get() = _builder.getMove()
      @JvmName("setMove")
      set(value) {
        _builder.setMove(value)
      }
    /**
     * <code>.base.Move move = 1;</code>
     */
    public fun clearMove() {
      _builder.clearMove()
    }
    /**
     * <code>.base.Move move = 1;</code>
     * @return Whether the move field is set.
     */
    public fun hasMove(): kotlin.Boolean {
      return _builder.hasMove()
    }

    /**
     * <code>.base.ClientAction action = 2;</code>
     */
    public var action: com.example.transport.ClientAction
      @JvmName("getAction")
      get() = _builder.getAction()
      @JvmName("setAction")
      set(value) {
        _builder.setAction(value)
      }
    /**
     * <code>.base.ClientAction action = 2;</code>
     */
    public fun clearAction() {
      _builder.clearAction()
    }
    /**
     * <code>.base.ClientAction action = 2;</code>
     * @return Whether the action field is set.
     */
    public fun hasAction(): kotlin.Boolean {
      return _builder.hasAction()
    }

    /**
     * <code>.base.GameParams params = 3;</code>
     */
    public var params: com.example.transport.GameParams
      @JvmName("getParams")
      get() = _builder.getParams()
      @JvmName("setParams")
      set(value) {
        _builder.setParams(value)
      }
    /**
     * <code>.base.GameParams params = 3;</code>
     */
    public fun clearParams() {
      _builder.clearParams()
    }
    /**
     * <code>.base.GameParams params = 3;</code>
     * @return Whether the params field is set.
     */
    public fun hasParams(): kotlin.Boolean {
      return _builder.hasParams()
    }
    public val payloadCase: com.example.transport.CreateRequest.PayloadCase
      @JvmName("getPayloadCase")
      get() = _builder.getPayloadCase()

    public fun clearPayload() {
      _builder.clearPayload()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.example.transport.CreateRequest.copy(block: com.example.transport.CreateRequestKt.Dsl.() -> kotlin.Unit): com.example.transport.CreateRequest =
  com.example.transport.CreateRequestKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public val com.example.transport.CreateRequestOrBuilder.moveOrNull: com.example.transport.Move?
  get() = if (hasMove()) getMove() else null

public val com.example.transport.CreateRequestOrBuilder.paramsOrNull: com.example.transport.GameParams?
  get() = if (hasParams()) getParams() else null

