//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: network.proto

package com.example.transport;

@kotlin.jvm.JvmName("-initializeinterruption")
public inline fun interruption(block: com.example.transport.InterruptionKt.Dsl.() -> kotlin.Unit): com.example.transport.Interruption =
  com.example.transport.InterruptionKt.Dsl._create(com.example.transport.Interruption.newBuilder()).apply { block() }._build()
public object InterruptionKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.example.transport.Interruption.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: com.example.transport.Interruption.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): com.example.transport.Interruption = _builder.build()

    /**
     * <code>.base.StopCause cause = 1;</code>
     */
    public var cause: com.example.transport.StopCause
      @JvmName("getCause")
      get() = _builder.getCause()
      @JvmName("setCause")
      set(value) {
        _builder.setCause(value)
      }
    /**
     * <code>.base.StopCause cause = 1;</code>
     */
    public fun clearCause() {
      _builder.clearCause()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.example.transport.Interruption.copy(block: com.example.transport.InterruptionKt.Dsl.() -> kotlin.Unit): com.example.transport.Interruption =
  com.example.transport.InterruptionKt.Dsl._create(this.toBuilder()).apply { block() }._build()

