//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: network.proto

package com.example.transport;

@kotlin.jvm.JvmName("-initializejoinRequest")
public inline fun joinRequest(block: com.example.transport.JoinRequestKt.Dsl.() -> kotlin.Unit): com.example.transport.JoinRequest =
  com.example.transport.JoinRequestKt.Dsl._create(com.example.transport.JoinRequest.newBuilder()).apply { block() }._build()
public object JoinRequestKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.example.transport.JoinRequest.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: com.example.transport.JoinRequest.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): com.example.transport.JoinRequest = _builder.build()

    /**
     * <code>.base.Move move = 1;</code>
     */
    public var move: com.example.transport.Move
      @JvmName("getMove")
      get() = _builder.getMove()
      @JvmName("setMove")
      set(value) {
        _builder.setMove(value)
      }
    /**
     * <code>.base.Move move = 1;</code>
     */
    public fun clearMove() {
      _builder.clearMove()
    }
    /**
     * <code>.base.Move move = 1;</code>
     * @return Whether the move field is set.
     */
    public fun hasMove(): kotlin.Boolean {
      return _builder.hasMove()
    }

    /**
     * <code>.base.ClientAction action = 2;</code>
     */
    public var action: com.example.transport.ClientAction
      @JvmName("getAction")
      get() = _builder.getAction()
      @JvmName("setAction")
      set(value) {
        _builder.setAction(value)
      }
    /**
     * <code>.base.ClientAction action = 2;</code>
     */
    public fun clearAction() {
      _builder.clearAction()
    }
    /**
     * <code>.base.ClientAction action = 2;</code>
     * @return Whether the action field is set.
     */
    public fun hasAction(): kotlin.Boolean {
      return _builder.hasAction()
    }

    /**
     * <code>uint32 game_id = 3;</code>
     */
    public var gameId: kotlin.Int
      @JvmName("getGameId")
      get() = _builder.getGameId()
      @JvmName("setGameId")
      set(value) {
        _builder.setGameId(value)
      }
    /**
     * <code>uint32 game_id = 3;</code>
     */
    public fun clearGameId() {
      _builder.clearGameId()
    }
    /**
     * <code>uint32 game_id = 3;</code>
     * @return Whether the gameId field is set.
     */
    public fun hasGameId(): kotlin.Boolean {
      return _builder.hasGameId()
    }
    public val payloadCase: com.example.transport.JoinRequest.PayloadCase
      @JvmName("getPayloadCase")
      get() = _builder.getPayloadCase()

    public fun clearPayload() {
      _builder.clearPayload()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.example.transport.JoinRequest.copy(block: com.example.transport.JoinRequestKt.Dsl.() -> kotlin.Unit): com.example.transport.JoinRequest =
  com.example.transport.JoinRequestKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public val com.example.transport.JoinRequestOrBuilder.moveOrNull: com.example.transport.Move?
  get() = if (hasMove()) getMove() else null

