//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: network.proto

package com.example.transport;

@kotlin.jvm.JvmName("-initializejoinResponse")
public inline fun joinResponse(block: com.example.transport.JoinResponseKt.Dsl.() -> kotlin.Unit): com.example.transport.JoinResponse =
  com.example.transport.JoinResponseKt.Dsl._create(com.example.transport.JoinResponse.newBuilder()).apply { block() }._build()
public object JoinResponseKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.example.transport.JoinResponse.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: com.example.transport.JoinResponse.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): com.example.transport.JoinResponse = _builder.build()

    /**
     * <code>.base.GameStatus status = 1;</code>
     */
    public var status: com.example.transport.GameStatus
      @JvmName("getStatus")
      get() = _builder.getStatus()
      @JvmName("setStatus")
      set(value) {
        _builder.setStatus(value)
      }
    /**
     * <code>.base.GameStatus status = 1;</code>
     */
    public fun clearStatus() {
      _builder.clearStatus()
    }
    /**
     * <code>.base.GameStatus status = 1;</code>
     * @return Whether the status field is set.
     */
    public fun hasStatus(): kotlin.Boolean {
      return _builder.hasStatus()
    }

    /**
     * <code>.base.WinLine win_line = 2;</code>
     */
    public var winLine: com.example.transport.WinLine
      @JvmName("getWinLine")
      get() = _builder.getWinLine()
      @JvmName("setWinLine")
      set(value) {
        _builder.setWinLine(value)
      }
    /**
     * <code>.base.WinLine win_line = 2;</code>
     */
    public fun clearWinLine() {
      _builder.clearWinLine()
    }
    /**
     * <code>.base.WinLine win_line = 2;</code>
     * @return Whether the winLine field is set.
     */
    public fun hasWinLine(): kotlin.Boolean {
      return _builder.hasWinLine()
    }

    /**
     * <code>optional .base.Move move = 4;</code>
     */
    public var move: com.example.transport.Move
      @JvmName("getMove")
      get() = _builder.getMove()
      @JvmName("setMove")
      set(value) {
        _builder.setMove(value)
      }
    /**
     * <code>optional .base.Move move = 4;</code>
     */
    public fun clearMove() {
      _builder.clearMove()
    }
    /**
     * <code>optional .base.Move move = 4;</code>
     * @return Whether the move field is set.
     */
    public fun hasMove(): kotlin.Boolean {
      return _builder.hasMove()
    }
    public val JoinResponseKt.Dsl.moveOrNull: com.example.transport.Move?
      get() = _builder.moveOrNull
    public val payloadCase: com.example.transport.JoinResponse.PayloadCase
      @JvmName("getPayloadCase")
      get() = _builder.getPayloadCase()

    public fun clearPayload() {
      _builder.clearPayload()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.example.transport.JoinResponse.copy(block: com.example.transport.JoinResponseKt.Dsl.() -> kotlin.Unit): com.example.transport.JoinResponse =
  com.example.transport.JoinResponseKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public val com.example.transport.JoinResponseOrBuilder.winLineOrNull: com.example.transport.WinLine?
  get() = if (hasWinLine()) getWinLine() else null

public val com.example.transport.JoinResponseOrBuilder.moveOrNull: com.example.transport.Move?
  get() = if (hasMove()) getMove() else null

