//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: network.proto

package com.example.transport;

@kotlin.jvm.JvmName("-initializelistItem")
public inline fun listItem(block: com.example.transport.ListItemKt.Dsl.() -> kotlin.Unit): com.example.transport.ListItem =
  com.example.transport.ListItemKt.Dsl._create(com.example.transport.ListItem.newBuilder()).apply { block() }._build()
public object ListItemKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.example.transport.ListItem.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: com.example.transport.ListItem.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): com.example.transport.ListItem = _builder.build()

    /**
     * <code>uint32 id = 1;</code>
     */
    public var id: kotlin.Int
      @JvmName("getId")
      get() = _builder.getId()
      @JvmName("setId")
      set(value) {
        _builder.setId(value)
      }
    /**
     * <code>uint32 id = 1;</code>
     */
    public fun clearId() {
      _builder.clearId()
    }

    /**
     * <code>.base.GameParams params = 2;</code>
     */
    public var params: com.example.transport.GameParams
      @JvmName("getParams")
      get() = _builder.getParams()
      @JvmName("setParams")
      set(value) {
        _builder.setParams(value)
      }
    /**
     * <code>.base.GameParams params = 2;</code>
     */
    public fun clearParams() {
      _builder.clearParams()
    }
    /**
     * <code>.base.GameParams params = 2;</code>
     * @return Whether the params field is set.
     */
    public fun hasParams(): kotlin.Boolean {
      return _builder.hasParams()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.example.transport.ListItem.copy(block: com.example.transport.ListItemKt.Dsl.() -> kotlin.Unit): com.example.transport.ListItem =
  com.example.transport.ListItemKt.Dsl._create(this.toBuilder()).apply { block() }._build()

public val com.example.transport.ListItemOrBuilder.paramsOrNull: com.example.transport.GameParams?
  get() = if (hasParams()) getParams() else null

