//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: network.proto

package com.example.transport;

@kotlin.jvm.JvmName("-initializerange")
public inline fun range(block: com.example.transport.RangeKt.Dsl.() -> kotlin.Unit): com.example.transport.Range =
  com.example.transport.RangeKt.Dsl._create(com.example.transport.Range.newBuilder()).apply { block() }._build()
public object RangeKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: com.example.transport.Range.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: com.example.transport.Range.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): com.example.transport.Range = _builder.build()

    /**
     * <code>uint32 start = 1;</code>
     */
    public var start: kotlin.Int
      @JvmName("getStart")
      get() = _builder.getStart()
      @JvmName("setStart")
      set(value) {
        _builder.setStart(value)
      }
    /**
     * <code>uint32 start = 1;</code>
     */
    public fun clearStart() {
      _builder.clearStart()
    }

    /**
     * <code>uint32 end = 2;</code>
     */
    public var end: kotlin.Int
      @JvmName("getEnd")
      get() = _builder.getEnd()
      @JvmName("setEnd")
      set(value) {
        _builder.setEnd(value)
      }
    /**
     * <code>uint32 end = 2;</code>
     */
    public fun clearEnd() {
      _builder.clearEnd()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun com.example.transport.Range.copy(block: com.example.transport.RangeKt.Dsl.() -> kotlin.Unit): com.example.transport.Range =
  com.example.transport.RangeKt.Dsl._create(this.toBuilder()).apply { block() }._build()

