// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: base.proto

package com.example.transport;

/**
 * Protobuf enum {@code base.ClientAction}
 */
public enum ClientAction
    implements com.google.protobuf.Internal.EnumLite {
  /**
   * <code>CLIENT_ACTION_LEAVE = 0;</code>
   */
  CLIENT_ACTION_LEAVE(0),
  /**
   * <code>CLIENT_ACTION_GIVE_UP = 1;</code>
   */
  CLIENT_ACTION_GIVE_UP(1),
  UNRECOGNIZED(-1),
  ;

  /**
   * <code>CLIENT_ACTION_LEAVE = 0;</code>
   */
  public static final int CLIENT_ACTION_LEAVE_VALUE = 0;
  /**
   * <code>CLIENT_ACTION_GIVE_UP = 1;</code>
   */
  public static final int CLIENT_ACTION_GIVE_UP_VALUE = 1;


  @java.lang.Override
  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @param value The number of the enum to look for.
   * @return The enum associated with the given number.
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static ClientAction valueOf(int value) {
    return forNumber(value);
  }

  public static ClientAction forNumber(int value) {
    switch (value) {
      case 0: return CLIENT_ACTION_LEAVE;
      case 1: return CLIENT_ACTION_GIVE_UP;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<ClientAction>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      ClientAction> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<ClientAction>() {
          @java.lang.Override
          public ClientAction findValueByNumber(int number) {
            return ClientAction.forNumber(number);
          }
        };

  public static com.google.protobuf.Internal.EnumVerifier 
      internalGetVerifier() {
    return ClientActionVerifier.INSTANCE;
  }

  private static final class ClientActionVerifier implements 
       com.google.protobuf.Internal.EnumVerifier { 
          static final com.google.protobuf.Internal.EnumVerifier           INSTANCE = new ClientActionVerifier();
          @java.lang.Override
          public boolean isInRange(int number) {
            return ClientAction.forNumber(number) != null;
          }
        };

  private final int value;

  private ClientAction(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:base.ClientAction)
}

