// automatically generated by the FlatBuffers compiler, do not modify

package com.example.transport;

public final class FollowUpMessage {
  private FollowUpMessage() { }
  public static final byte NONE = 0;
  public static final byte WinLine = 1;

  public static final String[] names = { "NONE", "WinLine", };

  public static String name(int e) { return names[e]; }
}

