// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: base.proto

package com.example.transport;

/**
 * Protobuf enum {@code base.GameStatus}
 */
public enum GameStatus
    implements com.google.protobuf.Internal.EnumLite {
  /**
   * <code>GAME_STATUS_UNSPECIFIED = 0;</code>
   */
  GAME_STATUS_UNSPECIFIED(0),
  /**
   * <code>GAME_STATUS_OK = 1;</code>
   */
  GAME_STATUS_OK(1),
  /**
   * <code>GAME_STATUS_TIE = 2;</code>
   */
  GAME_STATUS_TIE(2),
  /**
   * <code>GAME_STATUS_GAME_STARTED = 3;</code>
   */
  GAME_STATUS_GAME_STARTED(3),
  UNRECOGNIZED(-1),
  ;

  /**
   * <code>GAME_STATUS_UNSPECIFIED = 0;</code>
   */
  public static final int GAME_STATUS_UNSPECIFIED_VALUE = 0;
  /**
   * <code>GAME_STATUS_OK = 1;</code>
   */
  public static final int GAME_STATUS_OK_VALUE = 1;
  /**
   * <code>GAME_STATUS_TIE = 2;</code>
   */
  public static final int GAME_STATUS_TIE_VALUE = 2;
  /**
   * <code>GAME_STATUS_GAME_STARTED = 3;</code>
   */
  public static final int GAME_STATUS_GAME_STARTED_VALUE = 3;


  @java.lang.Override
  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @param value The number of the enum to look for.
   * @return The enum associated with the given number.
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static GameStatus valueOf(int value) {
    return forNumber(value);
  }

  public static GameStatus forNumber(int value) {
    switch (value) {
      case 0: return GAME_STATUS_UNSPECIFIED;
      case 1: return GAME_STATUS_OK;
      case 2: return GAME_STATUS_TIE;
      case 3: return GAME_STATUS_GAME_STARTED;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<GameStatus>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      GameStatus> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<GameStatus>() {
          @java.lang.Override
          public GameStatus findValueByNumber(int number) {
            return GameStatus.forNumber(number);
          }
        };

  public static com.google.protobuf.Internal.EnumVerifier 
      internalGetVerifier() {
    return GameStatusVerifier.INSTANCE;
  }

  private static final class GameStatusVerifier implements 
       com.google.protobuf.Internal.EnumVerifier { 
          static final com.google.protobuf.Internal.EnumVerifier           INSTANCE = new GameStatusVerifier();
          @java.lang.Override
          public boolean isInRange(int number) {
            return GameStatus.forNumber(number) != null;
          }
        };

  private final int value;

  private GameStatus(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:base.GameStatus)
}

