// automatically generated by the FlatBuffers compiler, do not modify

package com.example.transport;

public final class GameEventType {
  private GameEventType() { }
  public static final byte GameStarted = 0;
  public static final byte Win = 1;
  public static final byte Tie = 2;
  public static final byte OK = 3;
  public static final byte Cheating = 4;
  public static final byte OppCheating = 5;
  public static final byte Disonnected = 6;
  public static final byte OppDisconnected = 7;

  public static final String[] names = { "GameStarted", "Win", "Tie", "OK", "Cheating", "OppCheating", "Disonnected", "OppDisconnected", };

  public static String name(int e) { return names[e]; }
}

