// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: base.proto

package com.example.transport;

public interface GameParamsOrBuilder extends
    // @@protoc_insertion_point(interface_extends:base.GameParams)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>uint32 rows = 1;</code>
   * @return The rows.
   */
  int getRows();

  /**
   * <code>uint32 cols = 2;</code>
   * @return The cols.
   */
  int getCols();

  /**
   * <code>uint32 win = 3;</code>
   * @return The win.
   */
  int getWin();

  /**
   * <code>.base.MarkType mark = 4;</code>
   * @return The enum numeric value on the wire for mark.
   */
  int getMarkValue();
  /**
   * <code>.base.MarkType mark = 4;</code>
   * @return The mark.
   */
  com.example.transport.MarkType getMark();
}
