// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: base.proto

package com.example.transport;

/**
 * Protobuf enum {@code base.MarkType}
 */
public enum MarkType
    implements com.google.protobuf.Internal.EnumLite {
  /**
   * <code>MARK_TYPE_UNSPECIFIED = 0;</code>
   */
  MARK_TYPE_UNSPECIFIED(0),
  /**
   * <code>MARK_TYPE_CROSS = 1;</code>
   */
  MARK_TYPE_CROSS(1),
  /**
   * <code>MARK_TYPE_NOUGHT = 2;</code>
   */
  MARK_TYPE_NOUGHT(2),
  UNRECOGNIZED(-1),
  ;

  /**
   * <code>MARK_TYPE_UNSPECIFIED = 0;</code>
   */
  public static final int MARK_TYPE_UNSPECIFIED_VALUE = 0;
  /**
   * <code>MARK_TYPE_CROSS = 1;</code>
   */
  public static final int MARK_TYPE_CROSS_VALUE = 1;
  /**
   * <code>MARK_TYPE_NOUGHT = 2;</code>
   */
  public static final int MARK_TYPE_NOUGHT_VALUE = 2;


  @java.lang.Override
  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @param value The number of the enum to look for.
   * @return The enum associated with the given number.
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static MarkType valueOf(int value) {
    return forNumber(value);
  }

  public static MarkType forNumber(int value) {
    switch (value) {
      case 0: return MARK_TYPE_UNSPECIFIED;
      case 1: return MARK_TYPE_CROSS;
      case 2: return MARK_TYPE_NOUGHT;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<MarkType>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      MarkType> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<MarkType>() {
          @java.lang.Override
          public MarkType findValueByNumber(int number) {
            return MarkType.forNumber(number);
          }
        };

  public static com.google.protobuf.Internal.EnumVerifier 
      internalGetVerifier() {
    return MarkTypeVerifier.INSTANCE;
  }

  private static final class MarkTypeVerifier implements 
       com.google.protobuf.Internal.EnumVerifier { 
          static final com.google.protobuf.Internal.EnumVerifier           INSTANCE = new MarkTypeVerifier();
          @java.lang.Override
          public boolean isInRange(int number) {
            return MarkType.forNumber(number) != null;
          }
        };

  private final int value;

  private MarkType(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:base.MarkType)
}

