// automatically generated by the FlatBuffers compiler, do not modify

package com.example.transport;

public final class MarkTypeFilter {
  private MarkTypeFilter() { }
  public static final byte Cross = 0;
  public static final byte Nought = 1;
  public static final byte Any = 2;

  public static final String[] names = { "Cross", "Nought", "Any", };

  public static String name(int e) { return names[e]; }
}

