// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: base.proto

package com.example.transport;

/**
 * Protobuf type {@code base.Move}
 */
public  final class Move extends
    com.google.protobuf.GeneratedMessageLite<
        Move, Move.Builder> implements
    // @@protoc_insertion_point(message_implements:base.Move)
    MoveOrBuilder {
  private Move() {
  }
  public static final int ROW_FIELD_NUMBER = 1;
  private int row_;
  /**
   * <code>uint32 row = 1;</code>
   * @return The row.
   */
  @java.lang.Override
  public int getRow() {
    return row_;
  }
  /**
   * <code>uint32 row = 1;</code>
   * @param value The row to set.
   */
  private void setRow(int value) {
    
    row_ = value;
  }
  /**
   * <code>uint32 row = 1;</code>
   */
  private void clearRow() {
    
    row_ = 0;
  }

  public static final int COL_FIELD_NUMBER = 2;
  private int col_;
  /**
   * <code>uint32 col = 2;</code>
   * @return The col.
   */
  @java.lang.Override
  public int getCol() {
    return col_;
  }
  /**
   * <code>uint32 col = 2;</code>
   * @param value The col to set.
   */
  private void setCol(int value) {
    
    col_ = value;
  }
  /**
   * <code>uint32 col = 2;</code>
   */
  private void clearCol() {
    
    col_ = 0;
  }

  public static com.example.transport.Move parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.example.transport.Move parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.example.transport.Move parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.example.transport.Move parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.example.transport.Move parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.example.transport.Move parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.example.transport.Move parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.example.transport.Move parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static com.example.transport.Move parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }
  public static com.example.transport.Move parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static com.example.transport.Move parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.example.transport.Move parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return (Builder) DEFAULT_INSTANCE.createBuilder();
  }
  public static Builder newBuilder(com.example.transport.Move prototype) {
    return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
  }

  /**
   * Protobuf type {@code base.Move}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        com.example.transport.Move, Builder> implements
      // @@protoc_insertion_point(builder_implements:base.Move)
      com.example.transport.MoveOrBuilder {
    // Construct using com.example.transport.Move.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <code>uint32 row = 1;</code>
     * @return The row.
     */
    @java.lang.Override
    public int getRow() {
      return instance.getRow();
    }
    /**
     * <code>uint32 row = 1;</code>
     * @param value The row to set.
     * @return This builder for chaining.
     */
    public Builder setRow(int value) {
      copyOnWrite();
      instance.setRow(value);
      return this;
    }
    /**
     * <code>uint32 row = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearRow() {
      copyOnWrite();
      instance.clearRow();
      return this;
    }

    /**
     * <code>uint32 col = 2;</code>
     * @return The col.
     */
    @java.lang.Override
    public int getCol() {
      return instance.getCol();
    }
    /**
     * <code>uint32 col = 2;</code>
     * @param value The col to set.
     * @return This builder for chaining.
     */
    public Builder setCol(int value) {
      copyOnWrite();
      instance.setCol(value);
      return this;
    }
    /**
     * <code>uint32 col = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearCol() {
      copyOnWrite();
      instance.clearCol();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:base.Move)
  }
  @java.lang.Override
  @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
  protected final java.lang.Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      java.lang.Object arg0, java.lang.Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new com.example.transport.Move();
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case BUILD_MESSAGE_INFO: {
          java.lang.Object[] objects = new java.lang.Object[] {
            "row_",
            "col_",
          };
          java.lang.String info =
              "\u0000\u0002\u0000\u0000\u0001\u0002\u0002\u0000\u0000\u0000\u0001\u000b\u0002\u000b" +
              "";
          return newMessageInfo(DEFAULT_INSTANCE, info, objects);
      }
      // fall through
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        com.google.protobuf.Parser<com.example.transport.Move> parser = PARSER;
        if (parser == null) {
          synchronized (com.example.transport.Move.class) {
            parser = PARSER;
            if (parser == null) {
              parser =
                  new DefaultInstanceBasedParser<com.example.transport.Move>(
                      DEFAULT_INSTANCE);
              PARSER = parser;
            }
          }
        }
        return parser;
    }
    case GET_MEMOIZED_IS_INITIALIZED: {
      return (byte) 1;
    }
    case SET_MEMOIZED_IS_INITIALIZED: {
      return null;
    }
    }
    throw new UnsupportedOperationException();
  }


  // @@protoc_insertion_point(class_scope:base.Move)
  private static final com.example.transport.Move DEFAULT_INSTANCE;
  static {
    Move defaultInstance = new Move();
    // New instances are implicitly immutable so no need to make
    // immutable.
    DEFAULT_INSTANCE = defaultInstance;
    com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
      Move.class, defaultInstance);
  }

  public static com.example.transport.Move getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<Move> PARSER;

  public static com.google.protobuf.Parser<Move> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

