// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: base.proto

package com.example.transport;

public interface MoveOrBuilder extends
    // @@protoc_insertion_point(interface_extends:base.Move)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>uint32 row = 1;</code>
   * @return The row.
   */
  int getRow();

  /**
   * <code>uint32 col = 2;</code>
   * @return The col.
   */
  int getCol();
}
