// automatically generated by the FlatBuffers compiler, do not modify

package com.example.transport;

public final class PlainMessage {
  private PlainMessage() { }
  public static final byte NONE = 0;
  public static final byte Move = 1;
  public static final byte GameEvent = 2;

  public static final String[] names = { "NONE", "Move", "GameEvent", };

  public static String name(int e) { return names[e]; }
}

