// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: base.proto

package com.example.transport;

/**
 * Protobuf enum {@code base.StopCause}
 */
public enum StopCause
    implements com.google.protobuf.Internal.EnumLite {
  /**
   * <code>STOP_CAUSE_UNSPECIFIED = 0;</code>
   */
  STOP_CAUSE_UNSPECIFIED(0),
  /**
   * <code>STOP_CAUSE_DISCONNECT = 1;</code>
   */
  STOP_CAUSE_DISCONNECT(1),
  /**
   * <code>STOP_CAUSE_LEAVE = 2;</code>
   */
  STOP_CAUSE_LEAVE(2),
  /**
   * <code>STOP_CAUSE_INVALID_MOVE = 3;</code>
   */
  STOP_CAUSE_INVALID_MOVE(3),
  /**
   * <code>STOP_CAUSE_INTERNAL = 4;</code>
   */
  STOP_CAUSE_INTERNAL(4),
  UNRECOGNIZED(-1),
  ;

  /**
   * <code>STOP_CAUSE_UNSPECIFIED = 0;</code>
   */
  public static final int STOP_CAUSE_UNSPECIFIED_VALUE = 0;
  /**
   * <code>STOP_CAUSE_DISCONNECT = 1;</code>
   */
  public static final int STOP_CAUSE_DISCONNECT_VALUE = 1;
  /**
   * <code>STOP_CAUSE_LEAVE = 2;</code>
   */
  public static final int STOP_CAUSE_LEAVE_VALUE = 2;
  /**
   * <code>STOP_CAUSE_INVALID_MOVE = 3;</code>
   */
  public static final int STOP_CAUSE_INVALID_MOVE_VALUE = 3;
  /**
   * <code>STOP_CAUSE_INTERNAL = 4;</code>
   */
  public static final int STOP_CAUSE_INTERNAL_VALUE = 4;


  @java.lang.Override
  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @param value The number of the enum to look for.
   * @return The enum associated with the given number.
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static StopCause valueOf(int value) {
    return forNumber(value);
  }

  public static StopCause forNumber(int value) {
    switch (value) {
      case 0: return STOP_CAUSE_UNSPECIFIED;
      case 1: return STOP_CAUSE_DISCONNECT;
      case 2: return STOP_CAUSE_LEAVE;
      case 3: return STOP_CAUSE_INVALID_MOVE;
      case 4: return STOP_CAUSE_INTERNAL;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<StopCause>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      StopCause> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<StopCause>() {
          @java.lang.Override
          public StopCause findValueByNumber(int number) {
            return StopCause.forNumber(number);
          }
        };

  public static com.google.protobuf.Internal.EnumVerifier 
      internalGetVerifier() {
    return StopCauseVerifier.INSTANCE;
  }

  private static final class StopCauseVerifier implements 
       com.google.protobuf.Internal.EnumVerifier { 
          static final com.google.protobuf.Internal.EnumVerifier           INSTANCE = new StopCauseVerifier();
          @java.lang.Override
          public boolean isInRange(int number) {
            return StopCause.forNumber(number) != null;
          }
        };

  private final int value;

  private StopCause(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:base.StopCause)
}

