// automatically generated by the FlatBuffers compiler, do not modify

package com.example.game.networking.i9e;

import com.google.flatbuffers.BaseVector;
import com.google.flatbuffers.Constants;
import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.Table;

import java.nio.ByteBuffer;
import java.nio.ByteOrder;

import javax.annotation.Nullable;

@SuppressWarnings("unused")

@javax.annotation.Generated(value = "flatc")
public final class BluetoothCreator extends Table {
    public static void ValidateVersion() {
        Constants.FLATBUFFERS_1_12_0();
    }

    public static BluetoothCreator getRootAsBluetoothCreator(ByteBuffer _bb) {
        return getRootAsBluetoothCreator(_bb, new BluetoothCreator());
    }

    public static BluetoothCreator getRootAsBluetoothCreator(ByteBuffer _bb, BluetoothCreator obj) {
        _bb.order(ByteOrder.LITTLE_ENDIAN);
        return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb));
    }

    public void __init(int _i, ByteBuffer _bb) {
        __reset(_i, _bb);
    }

    public BluetoothCreator __assign(int _i, ByteBuffer _bb) {
        __init(_i, _bb);
        return this;
    }

    public byte msgType() {
        int o = __offset(4);
        return o != 0 ? bb.get(o + bb_pos) : 0;
    }

    public @Nullable
    Table msg(Table obj) {
        int o = __offset(6);
        return o != 0 ? __union(obj, o + bb_pos) : null;
    }

    public static int createBluetoothCreator(FlatBufferBuilder builder,
                                             byte msg_type,
                                             int msgOffset) {
        builder.startTable(2);
        BluetoothCreator.addMsg(builder, msgOffset);
        BluetoothCreator.addMsgType(builder, msg_type);
        return BluetoothCreator.endBluetoothCreator(builder);
    }

    public static void startBluetoothCreator(FlatBufferBuilder builder) {
        builder.startTable(2);
    }

    public static void addMsgType(FlatBufferBuilder builder, byte msgType) {
        builder.addByte(0, msgType, 0);
    }

    public static void addMsg(FlatBufferBuilder builder, int msgOffset) {
        builder.addOffset(1, msgOffset, 0);
    }

    public static int endBluetoothCreator(FlatBufferBuilder builder) {
        int o = builder.endTable();
        return o;
    }

    public static final class Vector extends BaseVector {
        public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) {
            __reset(_vector, _element_size, _bb);
            return this;
        }

        public BluetoothCreator get(int j) {
            return get(new BluetoothCreator(), j);
        }

        public BluetoothCreator get(BluetoothCreator obj, int j) {
            return obj.__assign(__indirect(__element(j), bb), bb);
        }
    }
}

