// automatically generated by the FlatBuffers compiler, do not modify

package com.example.game.networking.i9e;


@javax.annotation.Generated(value = "flatc")
public final class BluetoothCreatorMsg {
    private BluetoothCreatorMsg() {
    }

    public static final byte NONE = 0;
    public static final byte GameParams = 1;
    public static final byte Move = 2;
    public static final byte GameEvent = 3;

    public static final String[] names = {"NONE", "GameParams", "Move", "GameEvent",};

    public static String name(int e) {
        return names[e];
    }
}

