// automatically generated by the FlatBuffers compiler, do not modify

package com.example.game.networking.i9e;

import com.google.flatbuffers.Constants;
import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.Table;

import java.nio.ByteBuffer;
import java.nio.ByteOrder;

@SuppressWarnings("unused")

@javax.annotation.Generated(value = "flatc")
public final class GameId extends Table {
    public static void ValidateVersion() {
        Constants.FLATBUFFERS_1_11_1();
    }

    public static GameId getRootAsGameId(ByteBuffer _bb) {
        return getRootAsGameId(_bb, new GameId());
    }

    public static GameId getRootAsGameId(ByteBuffer _bb, GameId obj) {
        _bb.order(ByteOrder.LITTLE_ENDIAN);
        return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb));
    }

    public void __init(int _i, ByteBuffer _bb) {
        __reset(_i, _bb);
    }

    public GameId __assign(int _i, ByteBuffer _bb) {
        __init(_i, _bb);
        return this;
    }

    public short ID() {
        int o = __offset(4);
        return o != 0 ? bb.getShort(o + bb_pos) : 0;
    }

    public static int createGameId(FlatBufferBuilder builder,
                                   short ID) {
        builder.startTable(1);
        GameId.addID(builder, ID);
        return GameId.endGameId(builder);
    }

    public static void startGameId(FlatBufferBuilder builder) {
        builder.startTable(1);
    }

    public static void addID(FlatBufferBuilder builder, short ID) {
        builder.addShort(0, ID, 0);
    }

    public static int endGameId(FlatBufferBuilder builder) {
        int o = builder.endTable();
        return o;
    }
}

