// automatically generated by the FlatBuffers compiler, do not modify

package com.example.game.networking.i9e;

import com.google.flatbuffers.Constants;
import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.Table;

import java.nio.ByteBuffer;
import java.nio.ByteOrder;

import javax.annotation.Nullable;

@SuppressWarnings("unused")

@javax.annotation.Generated(value = "flatc")
public final class GameFilter extends Table {
    public static void ValidateVersion() {
        Constants.FLATBUFFERS_1_11_1();
    }

    public static GameFilter getRootAsGameFilter(ByteBuffer _bb) {
        return getRootAsGameFilter(_bb, new GameFilter());
    }

    public static GameFilter getRootAsGameFilter(ByteBuffer _bb, GameFilter obj) {
        _bb.order(ByteOrder.LITTLE_ENDIAN);
        return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb));
    }

    public void __init(int _i, ByteBuffer _bb) {
        __reset(_i, _bb);
    }

    public GameFilter __assign(int _i, ByteBuffer _bb) {
        __init(_i, _bb);
        return this;
    }

    public @Nullable
    Range rows() {
        return rows(new Range());
    }

    public @Nullable
    Range rows(Range obj) {
        int o = __offset(4);
        return o != 0 ? obj.__assign(__indirect(o + bb_pos), bb) : null;
    }

    public @Nullable
    Range cols() {
        return cols(new Range());
    }

    public @Nullable
    Range cols(Range obj) {
        int o = __offset(6);
        return o != 0 ? obj.__assign(__indirect(o + bb_pos), bb) : null;
    }

    public @Nullable
    Range win() {
        return win(new Range());
    }

    public @Nullable
    Range win(Range obj) {
        int o = __offset(8);
        return o != 0 ? obj.__assign(__indirect(o + bb_pos), bb) : null;
    }

    public byte mark() {
        int o = __offset(10);
        return o != 0 ? bb.get(o + bb_pos) : 0;
    }

    public static int createGameFilter(FlatBufferBuilder builder,
                                       int rowsOffset,
                                       int colsOffset,
                                       int winOffset,
                                       byte mark) {
        builder.startTable(4);
        GameFilter.addWin(builder, winOffset);
        GameFilter.addCols(builder, colsOffset);
        GameFilter.addRows(builder, rowsOffset);
        GameFilter.addMark(builder, mark);
        return GameFilter.endGameFilter(builder);
    }

    public static void startGameFilter(FlatBufferBuilder builder) {
        builder.startTable(4);
    }

    public static void addRows(FlatBufferBuilder builder, int rowsOffset) {
        builder.addOffset(0, rowsOffset, 0);
    }

    public static void addCols(FlatBufferBuilder builder, int colsOffset) {
        builder.addOffset(1, colsOffset, 0);
    }

    public static void addWin(FlatBufferBuilder builder, int winOffset) {
        builder.addOffset(2, winOffset, 0);
    }

    public static void addMark(FlatBufferBuilder builder, byte mark) {
        builder.addByte(3, mark, 0);
    }

    public static int endGameFilter(FlatBufferBuilder builder) {
        int o = builder.endTable();
        return o;
    }
}

