// automatically generated by the FlatBuffers compiler, do not modify

package com.example.game.networking.i9e;


@javax.annotation.Generated(value = "flatc")
public final class MarkType {
    private MarkType() {
    }

    public static final byte Cross = 0;
    public static final byte Nought = 1;

    public static final String[] names = {"Cross", "Nought",};

    public static String name(int e) {
        return names[e];
    }
}

