// automatically generated by the FlatBuffers compiler, do not modify

package com.example.game.networking.i9e;


@javax.annotation.Generated(value = "flatc")
public final class OpponentReqMsg {
    private OpponentReqMsg() {
    }

    public static final byte NONE = 0;
    public static final byte GameId = 1;
    public static final byte Move = 2;

    public static final String[] names = {"NONE", "GameId", "Move",};

    public static String name(int e) {
        return names[e];
    }
}

