// automatically generated by the FlatBuffers compiler, do not modify

package com.example.game.networking.i9e;


@javax.annotation.Generated(value = "flatc")
public final class OpponentRespMsg {
    private OpponentRespMsg() {
    }

    public static final byte NONE = 0;
    public static final byte Move = 1;
    public static final byte GameEvent = 2;

    public static final String[] names = {"NONE", "Move", "GameEvent",};

    public static String name(int e) {
        return names[e];
    }
}

