// automatically generated by the FlatBuffers compiler, do not modify

package com.example.game.networking.i9e;

import com.google.flatbuffers.Constants;
import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.Table;

import java.nio.ByteBuffer;
import java.nio.ByteOrder;

import javax.annotation.Nullable;

@SuppressWarnings("unused")

@javax.annotation.Generated(value = "flatc")
public final class OppRequest extends Table {
    public static void ValidateVersion() {
        Constants.FLATBUFFERS_1_11_1();
    }

    public static OppRequest getRootAsOppRequest(ByteBuffer _bb) {
        return getRootAsOppRequest(_bb, new OppRequest());
    }

    public static OppRequest getRootAsOppRequest(ByteBuffer _bb, OppRequest obj) {
        _bb.order(ByteOrder.LITTLE_ENDIAN);
        return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb));
    }

    public void __init(int _i, ByteBuffer _bb) {
        __reset(_i, _bb);
    }

    public OppRequest __assign(int _i, ByteBuffer _bb) {
        __init(_i, _bb);
        return this;
    }

    public byte reqType() {
        int o = __offset(4);
        return o != 0 ? bb.get(o + bb_pos) : 0;
    }

    public @Nullable
    Table req(Table obj) {
        int o = __offset(6);
        return o != 0 ? __union(obj, o) : null;
    }

    public static int createOppRequest(FlatBufferBuilder builder,
                                       byte req_type,
                                       int reqOffset) {
        builder.startTable(2);
        OppRequest.addReq(builder, reqOffset);
        OppRequest.addReqType(builder, req_type);
        return OppRequest.endOppRequest(builder);
    }

    public static void startOppRequest(FlatBufferBuilder builder) {
        builder.startTable(2);
    }

    public static void addReqType(FlatBufferBuilder builder, byte reqType) {
        builder.addByte(0, reqType, 0);
    }

    public static void addReq(FlatBufferBuilder builder, int reqOffset) {
        builder.addOffset(1, reqOffset, 0);
    }

    public static int endOppRequest(FlatBufferBuilder builder) {
        int o = builder.endTable();
        return o;
    }
}

