// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: bluetooth.proto

package com.example.transport;

public final class Bluetooth {
  private Bluetooth() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  static {
  }

  // @@protoc_insertion_point(outer_class_scope)
}
