// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: bluetooth.proto

package com.example.transport;

public interface ClientMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ClientMessage)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>.base.Move move = 1;</code>
   * @return Whether the move field is set.
   */
  boolean hasMove();
  /**
   * <code>.base.Move move = 1;</code>
   * @return The move.
   */
  com.example.transport.Move getMove();

  /**
   * <code>.base.ClientAction action = 2;</code>
   * @return Whether the action field is set.
   */
  boolean hasAction();
  /**
   * <code>.base.ClientAction action = 2;</code>
   * @return The enum numeric value on the wire for action.
   */
  int getActionValue();
  /**
   * <code>.base.ClientAction action = 2;</code>
   * @return The action.
   */
  com.example.transport.ClientAction getAction();

  public com.example.transport.ClientMessage.PayloadCase getPayloadCase();
}
