// automatically generated by the FlatBuffers compiler, do not modify

package com.example.transport;

public final class CreatorRespMsg {
  private CreatorRespMsg() { }
  public static final byte NONE = 0;
  public static final byte Move = 1;
  public static final byte GameId = 2;
  public static final byte GameEvent = 3;

  public static final String[] names = { "NONE", "Move", "GameId", "GameEvent", };

  public static String name(int e) { return names[e]; }
}

