// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: network.proto

package com.example.transport;

public interface CreateResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:transport.CreateResponse)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>.base.GameStatus status = 1;</code>
   * @return Whether the status field is set.
   */
  boolean hasStatus();
  /**
   * <code>.base.GameStatus status = 1;</code>
   * @return The enum numeric value on the wire for status.
   */
  int getStatusValue();
  /**
   * <code>.base.GameStatus status = 1;</code>
   * @return The status.
   */
  com.example.transport.GameStatus getStatus();

  /**
   * <code>.base.WinLine win_line = 2;</code>
   * @return Whether the winLine field is set.
   */
  boolean hasWinLine();
  /**
   * <code>.base.WinLine win_line = 2;</code>
   * @return The winLine.
   */
  com.example.transport.WinLine getWinLine();

  /**
   * <code>uint32 game_id = 4;</code>
   * @return Whether the gameId field is set.
   */
  boolean hasGameId();
  /**
   * <code>uint32 game_id = 4;</code>
   * @return The gameId.
   */
  int getGameId();

  /**
   * <code>optional .base.Move move = 5;</code>
   * @return Whether the move field is set.
   */
  boolean hasMove();
  /**
   * <code>optional .base.Move move = 5;</code>
   * @return The move.
   */
  com.example.transport.Move getMove();

  public com.example.transport.CreateResponse.PayloadCase getPayloadCase();
}
