// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: network.proto

package com.example.transport;

public interface GameFilterOrBuilder extends
    // @@protoc_insertion_point(interface_extends:transport.GameFilter)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>.transport.Range rows = 1;</code>
   * @return Whether the rows field is set.
   */
  boolean hasRows();
  /**
   * <code>.transport.Range rows = 1;</code>
   * @return The rows.
   */
  com.example.transport.Range getRows();

  /**
   * <code>.transport.Range cols = 2;</code>
   * @return Whether the cols field is set.
   */
  boolean hasCols();
  /**
   * <code>.transport.Range cols = 2;</code>
   * @return The cols.
   */
  com.example.transport.Range getCols();

  /**
   * <code>.transport.Range win = 3;</code>
   * @return Whether the win field is set.
   */
  boolean hasWin();
  /**
   * <code>.transport.Range win = 3;</code>
   * @return The win.
   */
  com.example.transport.Range getWin();

  /**
   * <code>.base.MarkType mark = 4;</code>
   * @return The enum numeric value on the wire for mark.
   */
  int getMarkValue();
  /**
   * <code>.base.MarkType mark = 4;</code>
   * @return The mark.
   */
  com.example.transport.MarkType getMark();
}
