// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: network.proto

package com.example.transport;

/**
 * Protobuf type {@code transport.GameFilter}
 */
public  final class GameFilter extends
    com.google.protobuf.GeneratedMessageLite<
        GameFilter, GameFilter.Builder> implements
    // @@protoc_insertion_point(message_implements:transport.GameFilter)
    GameFilterOrBuilder {
  private GameFilter() {
  }
  public static final int ROWS_FIELD_NUMBER = 1;
  private com.example.transport.Range rows_;
  /**
   * <code>.transport.Range rows = 1;</code>
   */
  @java.lang.Override
  public boolean hasRows() {
    return rows_ != null;
  }
  /**
   * <code>.transport.Range rows = 1;</code>
   */
  @java.lang.Override
  public com.example.transport.Range getRows() {
    return rows_ == null ? com.example.transport.Range.getDefaultInstance() : rows_;
  }
  /**
   * <code>.transport.Range rows = 1;</code>
   */
  private void setRows(com.example.transport.Range value) {
    value.getClass();
  rows_ = value;
    
    }
  /**
   * <code>.transport.Range rows = 1;</code>
   */
  @java.lang.SuppressWarnings({"ReferenceEquality"})
  private void mergeRows(com.example.transport.Range value) {
    value.getClass();
  if (rows_ != null &&
        rows_ != com.example.transport.Range.getDefaultInstance()) {
      rows_ =
        com.example.transport.Range.newBuilder(rows_).mergeFrom(value).buildPartial();
    } else {
      rows_ = value;
    }
    
  }
  /**
   * <code>.transport.Range rows = 1;</code>
   */
  private void clearRows() {  rows_ = null;
    
  }

  public static final int COLS_FIELD_NUMBER = 2;
  private com.example.transport.Range cols_;
  /**
   * <code>.transport.Range cols = 2;</code>
   */
  @java.lang.Override
  public boolean hasCols() {
    return cols_ != null;
  }
  /**
   * <code>.transport.Range cols = 2;</code>
   */
  @java.lang.Override
  public com.example.transport.Range getCols() {
    return cols_ == null ? com.example.transport.Range.getDefaultInstance() : cols_;
  }
  /**
   * <code>.transport.Range cols = 2;</code>
   */
  private void setCols(com.example.transport.Range value) {
    value.getClass();
  cols_ = value;
    
    }
  /**
   * <code>.transport.Range cols = 2;</code>
   */
  @java.lang.SuppressWarnings({"ReferenceEquality"})
  private void mergeCols(com.example.transport.Range value) {
    value.getClass();
  if (cols_ != null &&
        cols_ != com.example.transport.Range.getDefaultInstance()) {
      cols_ =
        com.example.transport.Range.newBuilder(cols_).mergeFrom(value).buildPartial();
    } else {
      cols_ = value;
    }
    
  }
  /**
   * <code>.transport.Range cols = 2;</code>
   */
  private void clearCols() {  cols_ = null;
    
  }

  public static final int WIN_FIELD_NUMBER = 3;
  private com.example.transport.Range win_;
  /**
   * <code>.transport.Range win = 3;</code>
   */
  @java.lang.Override
  public boolean hasWin() {
    return win_ != null;
  }
  /**
   * <code>.transport.Range win = 3;</code>
   */
  @java.lang.Override
  public com.example.transport.Range getWin() {
    return win_ == null ? com.example.transport.Range.getDefaultInstance() : win_;
  }
  /**
   * <code>.transport.Range win = 3;</code>
   */
  private void setWin(com.example.transport.Range value) {
    value.getClass();
  win_ = value;
    
    }
  /**
   * <code>.transport.Range win = 3;</code>
   */
  @java.lang.SuppressWarnings({"ReferenceEquality"})
  private void mergeWin(com.example.transport.Range value) {
    value.getClass();
  if (win_ != null &&
        win_ != com.example.transport.Range.getDefaultInstance()) {
      win_ =
        com.example.transport.Range.newBuilder(win_).mergeFrom(value).buildPartial();
    } else {
      win_ = value;
    }
    
  }
  /**
   * <code>.transport.Range win = 3;</code>
   */
  private void clearWin() {  win_ = null;
    
  }

  public static final int MARK_FIELD_NUMBER = 4;
  private int mark_;
  /**
   * <code>.base.MarkType mark = 4;</code>
   * @return The enum numeric value on the wire for mark.
   */
  @java.lang.Override
  public int getMarkValue() {
    return mark_;
  }
  /**
   * <code>.base.MarkType mark = 4;</code>
   * @return The mark.
   */
  @java.lang.Override
  public com.example.transport.MarkType getMark() {
    com.example.transport.MarkType result = com.example.transport.MarkType.forNumber(mark_);
    return result == null ? com.example.transport.MarkType.UNRECOGNIZED : result;
  }
  /**
   * <code>.base.MarkType mark = 4;</code>
   * @param value The enum numeric value on the wire for mark to set.
   */
  private void setMarkValue(int value) {
      mark_ = value;
  }
  /**
   * <code>.base.MarkType mark = 4;</code>
   * @param value The mark to set.
   */
  private void setMark(com.example.transport.MarkType value) {
    mark_ = value.getNumber();
    
  }
  /**
   * <code>.base.MarkType mark = 4;</code>
   */
  private void clearMark() {
    
    mark_ = 0;
  }

  public static com.example.transport.GameFilter parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.example.transport.GameFilter parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.example.transport.GameFilter parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.example.transport.GameFilter parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.example.transport.GameFilter parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.example.transport.GameFilter parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.example.transport.GameFilter parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.example.transport.GameFilter parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static com.example.transport.GameFilter parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }
  public static com.example.transport.GameFilter parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static com.example.transport.GameFilter parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.example.transport.GameFilter parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return (Builder) DEFAULT_INSTANCE.createBuilder();
  }
  public static Builder newBuilder(com.example.transport.GameFilter prototype) {
    return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
  }

  /**
   * Protobuf type {@code transport.GameFilter}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        com.example.transport.GameFilter, Builder> implements
      // @@protoc_insertion_point(builder_implements:transport.GameFilter)
      com.example.transport.GameFilterOrBuilder {
    // Construct using com.example.transport.GameFilter.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <code>.transport.Range rows = 1;</code>
     */
    @java.lang.Override
    public boolean hasRows() {
      return instance.hasRows();
    }
    /**
     * <code>.transport.Range rows = 1;</code>
     */
    @java.lang.Override
    public com.example.transport.Range getRows() {
      return instance.getRows();
    }
    /**
     * <code>.transport.Range rows = 1;</code>
     */
    public Builder setRows(com.example.transport.Range value) {
      copyOnWrite();
      instance.setRows(value);
      return this;
      }
    /**
     * <code>.transport.Range rows = 1;</code>
     */
    public Builder setRows(
        com.example.transport.Range.Builder builderForValue) {
      copyOnWrite();
      instance.setRows(builderForValue.build());
      return this;
    }
    /**
     * <code>.transport.Range rows = 1;</code>
     */
    public Builder mergeRows(com.example.transport.Range value) {
      copyOnWrite();
      instance.mergeRows(value);
      return this;
    }
    /**
     * <code>.transport.Range rows = 1;</code>
     */
    public Builder clearRows() {  copyOnWrite();
      instance.clearRows();
      return this;
    }

    /**
     * <code>.transport.Range cols = 2;</code>
     */
    @java.lang.Override
    public boolean hasCols() {
      return instance.hasCols();
    }
    /**
     * <code>.transport.Range cols = 2;</code>
     */
    @java.lang.Override
    public com.example.transport.Range getCols() {
      return instance.getCols();
    }
    /**
     * <code>.transport.Range cols = 2;</code>
     */
    public Builder setCols(com.example.transport.Range value) {
      copyOnWrite();
      instance.setCols(value);
      return this;
      }
    /**
     * <code>.transport.Range cols = 2;</code>
     */
    public Builder setCols(
        com.example.transport.Range.Builder builderForValue) {
      copyOnWrite();
      instance.setCols(builderForValue.build());
      return this;
    }
    /**
     * <code>.transport.Range cols = 2;</code>
     */
    public Builder mergeCols(com.example.transport.Range value) {
      copyOnWrite();
      instance.mergeCols(value);
      return this;
    }
    /**
     * <code>.transport.Range cols = 2;</code>
     */
    public Builder clearCols() {  copyOnWrite();
      instance.clearCols();
      return this;
    }

    /**
     * <code>.transport.Range win = 3;</code>
     */
    @java.lang.Override
    public boolean hasWin() {
      return instance.hasWin();
    }
    /**
     * <code>.transport.Range win = 3;</code>
     */
    @java.lang.Override
    public com.example.transport.Range getWin() {
      return instance.getWin();
    }
    /**
     * <code>.transport.Range win = 3;</code>
     */
    public Builder setWin(com.example.transport.Range value) {
      copyOnWrite();
      instance.setWin(value);
      return this;
      }
    /**
     * <code>.transport.Range win = 3;</code>
     */
    public Builder setWin(
        com.example.transport.Range.Builder builderForValue) {
      copyOnWrite();
      instance.setWin(builderForValue.build());
      return this;
    }
    /**
     * <code>.transport.Range win = 3;</code>
     */
    public Builder mergeWin(com.example.transport.Range value) {
      copyOnWrite();
      instance.mergeWin(value);
      return this;
    }
    /**
     * <code>.transport.Range win = 3;</code>
     */
    public Builder clearWin() {  copyOnWrite();
      instance.clearWin();
      return this;
    }

    /**
     * <code>.base.MarkType mark = 4;</code>
     * @return The enum numeric value on the wire for mark.
     */
    @java.lang.Override
    public int getMarkValue() {
      return instance.getMarkValue();
    }
    /**
     * <code>.base.MarkType mark = 4;</code>
     * @param value The mark to set.
     * @return This builder for chaining.
     */
    public Builder setMarkValue(int value) {
      copyOnWrite();
      instance.setMarkValue(value);
      return this;
    }
    /**
     * <code>.base.MarkType mark = 4;</code>
     * @return The mark.
     */
    @java.lang.Override
    public com.example.transport.MarkType getMark() {
      return instance.getMark();
    }
    /**
     * <code>.base.MarkType mark = 4;</code>
     * @param value The enum numeric value on the wire for mark to set.
     * @return This builder for chaining.
     */
    public Builder setMark(com.example.transport.MarkType value) {
      copyOnWrite();
      instance.setMark(value);
      return this;
    }
    /**
     * <code>.base.MarkType mark = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearMark() {
      copyOnWrite();
      instance.clearMark();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:transport.GameFilter)
  }
  @java.lang.Override
  @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
  protected final java.lang.Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      java.lang.Object arg0, java.lang.Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new com.example.transport.GameFilter();
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case BUILD_MESSAGE_INFO: {
          java.lang.Object[] objects = new java.lang.Object[] {
            "rows_",
            "cols_",
            "win_",
            "mark_",
          };
          java.lang.String info =
              "\u0000\u0004\u0000\u0000\u0001\u0004\u0004\u0000\u0000\u0000\u0001\t\u0002\t\u0003" +
              "\t\u0004\f";
          return newMessageInfo(DEFAULT_INSTANCE, info, objects);
      }
      // fall through
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        com.google.protobuf.Parser<com.example.transport.GameFilter> parser = PARSER;
        if (parser == null) {
          synchronized (com.example.transport.GameFilter.class) {
            parser = PARSER;
            if (parser == null) {
              parser =
                  new DefaultInstanceBasedParser<com.example.transport.GameFilter>(
                      DEFAULT_INSTANCE);
              PARSER = parser;
            }
          }
        }
        return parser;
    }
    case GET_MEMOIZED_IS_INITIALIZED: {
      return (byte) 1;
    }
    case SET_MEMOIZED_IS_INITIALIZED: {
      return null;
    }
    }
    throw new UnsupportedOperationException();
  }


  // @@protoc_insertion_point(class_scope:transport.GameFilter)
  private static final com.example.transport.GameFilter DEFAULT_INSTANCE;
  static {
    GameFilter defaultInstance = new GameFilter();
    // New instances are implicitly immutable so no need to make
    // immutable.
    DEFAULT_INSTANCE = defaultInstance;
    com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
      GameFilter.class, defaultInstance);
  }

  public static com.example.transport.GameFilter getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<GameFilter> PARSER;

  public static com.google.protobuf.Parser<GameFilter> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

