// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: network.proto

package com.example.transport;

public interface InterruptionOrBuilder extends
    // @@protoc_insertion_point(interface_extends:transport.Interruption)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>.base.StopCause cause = 1;</code>
   * @return The enum numeric value on the wire for cause.
   */
  int getCauseValue();
  /**
   * <code>.base.StopCause cause = 1;</code>
   * @return The cause.
   */
  com.example.transport.StopCause getCause();
}
