// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: network.proto

package com.example.transport;

/**
 * Protobuf type {@code transport.Interruption}
 */
public  final class Interruption extends
    com.google.protobuf.GeneratedMessageLite<
        Interruption, Interruption.Builder> implements
    // @@protoc_insertion_point(message_implements:transport.Interruption)
    InterruptionOrBuilder {
  private Interruption() {
  }
  public static final int CAUSE_FIELD_NUMBER = 1;
  private int cause_;
  /**
   * <code>.base.StopCause cause = 1;</code>
   * @return The enum numeric value on the wire for cause.
   */
  @java.lang.Override
  public int getCauseValue() {
    return cause_;
  }
  /**
   * <code>.base.StopCause cause = 1;</code>
   * @return The cause.
   */
  @java.lang.Override
  public com.example.transport.StopCause getCause() {
    com.example.transport.StopCause result = com.example.transport.StopCause.forNumber(cause_);
    return result == null ? com.example.transport.StopCause.UNRECOGNIZED : result;
  }
  /**
   * <code>.base.StopCause cause = 1;</code>
   * @param value The enum numeric value on the wire for cause to set.
   */
  private void setCauseValue(int value) {
      cause_ = value;
  }
  /**
   * <code>.base.StopCause cause = 1;</code>
   * @param value The cause to set.
   */
  private void setCause(com.example.transport.StopCause value) {
    cause_ = value.getNumber();
    
  }
  /**
   * <code>.base.StopCause cause = 1;</code>
   */
  private void clearCause() {
    
    cause_ = 0;
  }

  public static com.example.transport.Interruption parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.example.transport.Interruption parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.example.transport.Interruption parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.example.transport.Interruption parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.example.transport.Interruption parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.example.transport.Interruption parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.example.transport.Interruption parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.example.transport.Interruption parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static com.example.transport.Interruption parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }
  public static com.example.transport.Interruption parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static com.example.transport.Interruption parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.example.transport.Interruption parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return (Builder) DEFAULT_INSTANCE.createBuilder();
  }
  public static Builder newBuilder(com.example.transport.Interruption prototype) {
    return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
  }

  /**
   * Protobuf type {@code transport.Interruption}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        com.example.transport.Interruption, Builder> implements
      // @@protoc_insertion_point(builder_implements:transport.Interruption)
      com.example.transport.InterruptionOrBuilder {
    // Construct using com.example.transport.Interruption.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <code>.base.StopCause cause = 1;</code>
     * @return The enum numeric value on the wire for cause.
     */
    @java.lang.Override
    public int getCauseValue() {
      return instance.getCauseValue();
    }
    /**
     * <code>.base.StopCause cause = 1;</code>
     * @param value The cause to set.
     * @return This builder for chaining.
     */
    public Builder setCauseValue(int value) {
      copyOnWrite();
      instance.setCauseValue(value);
      return this;
    }
    /**
     * <code>.base.StopCause cause = 1;</code>
     * @return The cause.
     */
    @java.lang.Override
    public com.example.transport.StopCause getCause() {
      return instance.getCause();
    }
    /**
     * <code>.base.StopCause cause = 1;</code>
     * @param value The enum numeric value on the wire for cause to set.
     * @return This builder for chaining.
     */
    public Builder setCause(com.example.transport.StopCause value) {
      copyOnWrite();
      instance.setCause(value);
      return this;
    }
    /**
     * <code>.base.StopCause cause = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearCause() {
      copyOnWrite();
      instance.clearCause();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:transport.Interruption)
  }
  @java.lang.Override
  @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
  protected final java.lang.Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      java.lang.Object arg0, java.lang.Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new com.example.transport.Interruption();
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case BUILD_MESSAGE_INFO: {
          java.lang.Object[] objects = new java.lang.Object[] {
            "cause_",
          };
          java.lang.String info =
              "\u0000\u0001\u0000\u0000\u0001\u0001\u0001\u0000\u0000\u0000\u0001\f";
          return newMessageInfo(DEFAULT_INSTANCE, info, objects);
      }
      // fall through
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        com.google.protobuf.Parser<com.example.transport.Interruption> parser = PARSER;
        if (parser == null) {
          synchronized (com.example.transport.Interruption.class) {
            parser = PARSER;
            if (parser == null) {
              parser =
                  new DefaultInstanceBasedParser<com.example.transport.Interruption>(
                      DEFAULT_INSTANCE);
              PARSER = parser;
            }
          }
        }
        return parser;
    }
    case GET_MEMOIZED_IS_INITIALIZED: {
      return (byte) 1;
    }
    case SET_MEMOIZED_IS_INITIALIZED: {
      return null;
    }
    }
    throw new UnsupportedOperationException();
  }


  // @@protoc_insertion_point(class_scope:transport.Interruption)
  private static final com.example.transport.Interruption DEFAULT_INSTANCE;
  static {
    Interruption defaultInstance = new Interruption();
    // New instances are implicitly immutable so no need to make
    // immutable.
    DEFAULT_INSTANCE = defaultInstance;
    com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
      Interruption.class, defaultInstance);
  }

  public static com.example.transport.Interruption getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<Interruption> PARSER;

  public static com.google.protobuf.Parser<Interruption> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

