// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: network.proto

package com.example.transport;

/**
 * Protobuf type {@code transport.ListItem}
 */
public  final class ListItem extends
    com.google.protobuf.GeneratedMessageLite<
        ListItem, ListItem.Builder> implements
    // @@protoc_insertion_point(message_implements:transport.ListItem)
    ListItemOrBuilder {
  private ListItem() {
  }
  public static final int ID_FIELD_NUMBER = 1;
  private int id_;
  /**
   * <code>uint32 id = 1;</code>
   * @return The id.
   */
  @java.lang.Override
  public int getId() {
    return id_;
  }
  /**
   * <code>uint32 id = 1;</code>
   * @param value The id to set.
   */
  private void setId(int value) {
    
    id_ = value;
  }
  /**
   * <code>uint32 id = 1;</code>
   */
  private void clearId() {
    
    id_ = 0;
  }

  public static final int PARAMS_FIELD_NUMBER = 2;
  private com.example.transport.GameParams params_;
  /**
   * <code>.base.GameParams params = 2;</code>
   */
  @java.lang.Override
  public boolean hasParams() {
    return params_ != null;
  }
  /**
   * <code>.base.GameParams params = 2;</code>
   */
  @java.lang.Override
  public com.example.transport.GameParams getParams() {
    return params_ == null ? com.example.transport.GameParams.getDefaultInstance() : params_;
  }
  /**
   * <code>.base.GameParams params = 2;</code>
   */
  private void setParams(com.example.transport.GameParams value) {
    value.getClass();
  params_ = value;
    
    }
  /**
   * <code>.base.GameParams params = 2;</code>
   */
  @java.lang.SuppressWarnings({"ReferenceEquality"})
  private void mergeParams(com.example.transport.GameParams value) {
    value.getClass();
  if (params_ != null &&
        params_ != com.example.transport.GameParams.getDefaultInstance()) {
      params_ =
        com.example.transport.GameParams.newBuilder(params_).mergeFrom(value).buildPartial();
    } else {
      params_ = value;
    }
    
  }
  /**
   * <code>.base.GameParams params = 2;</code>
   */
  private void clearParams() {  params_ = null;
    
  }

  public static com.example.transport.ListItem parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.example.transport.ListItem parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.example.transport.ListItem parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.example.transport.ListItem parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.example.transport.ListItem parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static com.example.transport.ListItem parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static com.example.transport.ListItem parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.example.transport.ListItem parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static com.example.transport.ListItem parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }
  public static com.example.transport.ListItem parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static com.example.transport.ListItem parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static com.example.transport.ListItem parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return (Builder) DEFAULT_INSTANCE.createBuilder();
  }
  public static Builder newBuilder(com.example.transport.ListItem prototype) {
    return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
  }

  /**
   * Protobuf type {@code transport.ListItem}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        com.example.transport.ListItem, Builder> implements
      // @@protoc_insertion_point(builder_implements:transport.ListItem)
      com.example.transport.ListItemOrBuilder {
    // Construct using com.example.transport.ListItem.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <code>uint32 id = 1;</code>
     * @return The id.
     */
    @java.lang.Override
    public int getId() {
      return instance.getId();
    }
    /**
     * <code>uint32 id = 1;</code>
     * @param value The id to set.
     * @return This builder for chaining.
     */
    public Builder setId(int value) {
      copyOnWrite();
      instance.setId(value);
      return this;
    }
    /**
     * <code>uint32 id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearId() {
      copyOnWrite();
      instance.clearId();
      return this;
    }

    /**
     * <code>.base.GameParams params = 2;</code>
     */
    @java.lang.Override
    public boolean hasParams() {
      return instance.hasParams();
    }
    /**
     * <code>.base.GameParams params = 2;</code>
     */
    @java.lang.Override
    public com.example.transport.GameParams getParams() {
      return instance.getParams();
    }
    /**
     * <code>.base.GameParams params = 2;</code>
     */
    public Builder setParams(com.example.transport.GameParams value) {
      copyOnWrite();
      instance.setParams(value);
      return this;
      }
    /**
     * <code>.base.GameParams params = 2;</code>
     */
    public Builder setParams(
        com.example.transport.GameParams.Builder builderForValue) {
      copyOnWrite();
      instance.setParams(builderForValue.build());
      return this;
    }
    /**
     * <code>.base.GameParams params = 2;</code>
     */
    public Builder mergeParams(com.example.transport.GameParams value) {
      copyOnWrite();
      instance.mergeParams(value);
      return this;
    }
    /**
     * <code>.base.GameParams params = 2;</code>
     */
    public Builder clearParams() {  copyOnWrite();
      instance.clearParams();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:transport.ListItem)
  }
  @java.lang.Override
  @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
  protected final java.lang.Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      java.lang.Object arg0, java.lang.Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new com.example.transport.ListItem();
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case BUILD_MESSAGE_INFO: {
          java.lang.Object[] objects = new java.lang.Object[] {
            "id_",
            "params_",
          };
          java.lang.String info =
              "\u0000\u0002\u0000\u0000\u0001\u0002\u0002\u0000\u0000\u0000\u0001\u000b\u0002\t" +
              "";
          return newMessageInfo(DEFAULT_INSTANCE, info, objects);
      }
      // fall through
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        com.google.protobuf.Parser<com.example.transport.ListItem> parser = PARSER;
        if (parser == null) {
          synchronized (com.example.transport.ListItem.class) {
            parser = PARSER;
            if (parser == null) {
              parser =
                  new DefaultInstanceBasedParser<com.example.transport.ListItem>(
                      DEFAULT_INSTANCE);
              PARSER = parser;
            }
          }
        }
        return parser;
    }
    case GET_MEMOIZED_IS_INITIALIZED: {
      return (byte) 1;
    }
    case SET_MEMOIZED_IS_INITIALIZED: {
      return null;
    }
    }
    throw new UnsupportedOperationException();
  }


  // @@protoc_insertion_point(class_scope:transport.ListItem)
  private static final com.example.transport.ListItem DEFAULT_INSTANCE;
  static {
    ListItem defaultInstance = new ListItem();
    // New instances are implicitly immutable so no need to make
    // immutable.
    DEFAULT_INSTANCE = defaultInstance;
    com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
      ListItem.class, defaultInstance);
  }

  public static com.example.transport.ListItem getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<ListItem> PARSER;

  public static com.google.protobuf.Parser<ListItem> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

