// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: network.proto

package com.example.transport;

public interface ListItemOrBuilder extends
    // @@protoc_insertion_point(interface_extends:transport.ListItem)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>uint32 id = 1;</code>
   * @return The id.
   */
  int getId();

  /**
   * <code>.base.GameParams params = 2;</code>
   * @return Whether the params field is set.
   */
  boolean hasParams();
  /**
   * <code>.base.GameParams params = 2;</code>
   * @return The params.
   */
  com.example.transport.GameParams getParams();
}
