// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: network.proto

package com.example.transport;

public interface RangeOrBuilder extends
    // @@protoc_insertion_point(interface_extends:transport.Range)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>uint32 start = 1;</code>
   * @return The start.
   */
  int getStart();

  /**
   * <code>uint32 end = 2;</code>
   * @return The end.
   */
  int getEnd();
}
